export const ROLES = {
  SUPER_ADMINISTRADOR: 'SUPER_ADMINISTRADOR',
  ADMINISTRADOR_EMPRESA: 'ADMINISTRADOR_EMPRESA',
  ADMINISTRADOR_SUCURSAL: 'ADMINISTRADOR_SUCURSAL',
  VISUALIZADOR: 'VISUALIZADOR',
} as const

export type RoleName = (typeof ROLES)[keyof typeof ROLES]
